
-- ==========================================
-- 1. Tabel Kategori
-- ==========================================
CREATE TABLE "kategori" (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "nama_kategori" VARCHAR2(100) NOT NULL
);

-- ==========================================
-- 2. Tabel Users
-- PENTING: Kolom "level" tetap harus pakai kutip dua karena itu kata kunci Oracle
-- ==========================================
CREATE TABLE "users" (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "username" VARCHAR2(50) NOT NULL,
    "password" VARCHAR2(255) NOT NULL,
    "level" VARCHAR2(10) DEFAULT 'user', 
    CONSTRAINT "uq_username" UNIQUE ("username"),
    CONSTRAINT "chk_user_level" CHECK ("level" IN ('admin', 'user'))
);

-- ==========================================
-- 3. Tabel Wisata
-- ==========================================
CREATE TABLE "wisata" (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "nama_wisata" VARCHAR2(100),
    "lokasi" VARCHAR2(100),
    "kategori" VARCHAR2(50),
    "deskripsi" CLOB, -- Text di MySQL jadi CLOB di Oracle
    "harga_tiket" NUMBER(10,2) DEFAULT 0,
    "jam_operasional" VARCHAR2(100) DEFAULT '08:00 - 17:00',
    "link_google_map" CLOB,
    "fasilitas" CLOB,
    "gambar" VARCHAR2(255),
    "tanggal_upload" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 4. Tabel Wisata Galeri
-- ==========================================
CREATE TABLE "wisata_galeri" (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "id_wisata" NUMBER,
    "nama_file" VARCHAR2(255),
    CONSTRAINT "fk_galeri_wisata" FOREIGN KEY ("id_wisata") 
        REFERENCES "wisata"("id") ON DELETE CASCADE
);

-- ==========================================
-- 5. Tabel Transaksi
-- ==========================================
CREATE TABLE "transaksi" (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "kode_transaksi" VARCHAR2(20) NOT NULL,
    "id_user" NUMBER NOT NULL,
    "id_wisata" NUMBER NOT NULL,
    "tanggal_kunjungan" DATE NOT NULL,
    "jumlah_tiket" NUMBER NOT NULL,
    "total_harga" NUMBER(10,2) NOT NULL,
    "status" VARCHAR2(20) DEFAULT 'confirmed',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_transaksi_user" FOREIGN KEY ("id_user") REFERENCES "users"("id"),
    CONSTRAINT "fk_transaksi_wisata" FOREIGN KEY ("id_wisata") REFERENCES "wisata"("id"),
    CONSTRAINT "chk_status" CHECK ("status" IN ('pending', 'confirmed', 'completed', 'cancelled'))
);

-- ==========================================
-- INSERT DATA
-- ==========================================
INSERT INTO "kategori" ("nama_kategori") VALUES ('Pantai');
INSERT INTO "kategori" ("nama_kategori") VALUES ('Gunung');
INSERT INTO "kategori" ("nama_kategori") VALUES ('Alam');
INSERT INTO "kategori" ("nama_kategori") VALUES ('Budaya');
INSERT INTO "kategori" ("nama_kategori") VALUES ('Kuliner');

INSERT INTO "users" ("username", "password", "level") 
VALUES ('admin', '$2y$10$IScRN2WdhE17xVO7KgEqHu3ugaXHSZX2QwN9i4EMekg6ROUYLu2bO', 'admin');

INSERT INTO "users" ("username", "password", "level") 
VALUES ('user', '$2y$10$ZX1ZQ596zKifbJJjPbWnYOefl5TvUnuHrzMV/KonM6AANqWUJD53.', 'user');

COMMIT;









